### ISSUE TITLE
Exporting JSON columns

### ISSUE THREAD

**Issue by chintogtokh** [yii2tech/spreadsheet#8]
I haven't been able to dig in *too* deep here but even though this library and yii2tech/csv-grid both seem to be almost identical in config and functionality, CsvGrid exports JSON columns without issue while this library just skips over them, with identical options (data provider, column config). What could be the issue here?

**Comment by klimov-paul** [comment]
"phpoffice/phpspreadsheet" library can not render cell content from array or object due to its internal checks:
https://github.com/PHPOffice/PhpSpreadsheet/blob/1.3.1/src/PhpSpreadsheet/Cell/DefaultValueBinder.php#L62

If it is concern to you should report the issue to [phpoffice/phpspreadsheet](https://github.com/PHPOffice/PhpSpreadsheet) project.
